name: "Sign Release with Cosign"
description: "Install cosign, sign the release file, and upload the cosign bundle"
author: "Diode Inc."

inputs:
  path:
    description: "Path to the file to sign"
    required: true
  upload:
    description: "Whether to upload the cosign bundle as an artifact"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.9.2

    - name: Sign Release
      id: sign
      shell: bash
      run: |
        file_name=$(basename "${{ inputs.path }}")
        cosign sign-blob "${{ inputs.path }}" --bundle "${file_name}.cosign.json" --yes
        echo "bundle_name=${file_name}.cosign.json" >> "$GITHUB_OUTPUT"

    - name: Upload Cosign Bundle
      if: inputs.upload == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.sign.outputs.bundle_name }}.zip
        path: "*.cosign.json"
        retention-days: 30
