name: "PCB Release Action"
description: "Run pcb release for a single .zen file inside the official KiCad container."
author: "Diode Inc."

inputs:
  file:
    description: "Path to a .zen file (absolute or workspace-relative)"
    required: true

outputs:
  archive:
    description: "Absolute path to the produced release archive (.zip)"
  version:
    description: "Version string produced by pcb release"

runs:
  using: "docker"
  image: "Dockerfile"
