name: 'PCB Release Action'
description: 'Run pcb release for provided paths inside the official KiCad container.'
author: 'Diode Inc.'

inputs:
  paths:
    description: 'List of paths (dirs or .zen files), comma or newline separated'
    required: true

outputs:
  artifact-dir:
    description: 'Directory containing collected release archives'
  artifact-files:
    description: 'Newline-separated list of collected archives (relative paths)'

runs:
  using: 'docker'
  image: 'Dockerfile'
