name: "Detect PCB Boards"
description: "Detect all PCB boards in the repository"
author: "Diode Inc."

outputs:
  boards:
    description: "JSON array of detected board names"
    value: ${{ steps.discover.outputs.boards }}

runs:
  using: "composite"
  steps:
    - name: Discover boards
      id: discover
      shell: bash
      run: |
        echo "boards=$(pcb info -f json | jq -c '[.boards[].name]')" >> "$GITHUB_OUTPUT"
