name: "Setup PCB CLI"
description: "Install the pcb CLI tool on the runner"
author: "Diode Inc."

inputs:
  version:
    description: "Version of pcb CLI to install (default: latest)"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Setup Rust (for HEAD version)
      if: ${{ inputs.version == 'HEAD' }}
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install pcb CLI
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "HEAD" ]; then
          cargo install --git https://github.com/diodeinc/pcb pcb
        elif [ "${{ inputs.version }}" = "latest" ]; then
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/diodeinc/pcb/releases/latest/download/pcb-installer.sh | sh
        else
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/diodeinc/pcb/releases/download/${{ inputs.version }}/pcb-installer.sh | sh
        fi
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        export PATH="$HOME/.cargo/bin:$PATH"
        pcb --version
