name: PCB Release

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  detect:
    name: Detect boards
    runs-on: ubuntu-latest
    outputs:
      boards: ${{ steps.detect.outputs.boards }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install pcb
        uses: diodeinc/pcb-action/setup@v2

      - name: Detect boards
        id: detect
        uses: diodeinc/pcb-action/detect@v2

  release:
    name: Release ${{ matrix.board }}
    needs: detect
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:9.0.3
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        board: ${{ fromJSON(needs.detect.outputs.boards) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: apt-get update && apt-get install -y curl jq git

      - name: Fix git permissions
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install pcb
        uses: diodeinc/pcb-action/setup@v2

      - name: Release
        id: release
        uses: diodeinc/pcb-action/release@v2
        with:
          board: ${{ matrix.board }}

      - name: Sign
        uses: diodeinc/pcb-action/sign@v2
        with:
          path: ${{ steps.release.outputs.archive_path }}
